#!/bin/sh

case $1 in
	start)
		echo ">>> loading AESDCHAR..."
		aesdchar_load

		echo ">>> loading TEMPDRIVER..."
		tempdriver_load

		echo ">>> Kernel modules loaded"
		;;
	stop)
		tempdriver_unload
		aesdchar_unload

		echo ">> Kernel modules unloaded"
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
